### ISSUE TITLE
Usage of 'actions' in endpoints

### ISSUE THREAD

**Issue by openmosix** [Gild/gild-api#7]
How do we feel about https://github.com/Gild/gild-api#actions ?

cc: @tejo @andreacfm @taganaka

**Comment by tejo** [comment]
Generally speaking I'm ok with actions, but lately, speaking with @andreacfm and stefano, I liked the idea to have resource instead of actions, eg:

```
instead of having:

POST /article/:id/actions/publish
POST /article/:id/actions/unpublish

having:

POST /article/:id/article_publication
DELETE /article/:id/article_publication
```

**Comment by stefanoc** [comment]
My (very strong) position is that custom verbs should be a last-resort mean of handling cases where you cannot come up with a sensible noun on which you can operate with standard CRUD semantics.
:+1: on relegating them to a fixed namespace (i.e. ``.../actions/:name``)

**Comment by andreacfm** [comment]
@tejo @stefanoc 
Can we try to define a sort of generic rule (maybe with some examples) of where should be the case to use an action.
When we discussed this was not easy to find a correct naming for actions like users/suspend and users/enable. Is this a suitable example as case where using actions?

**Comment by stefanoc** [comment]
If you think about it the suspend/resume actions are just means of changing a user's _status_:

```json
GET /users/1/status
{
  "data": {
    "type": "user_status",
    "id": "1",
    "attributes": {
      "active": true
    }
  }
}
```
```json
PATCH /users/1/status``
{
  "data": {
    "type": "user_status",
    "id": "1",
    "attributes": {
      "active": false
    }
  }
}
```

**Comment by andreacfm** [comment]
@stefanoc A user **status** could be related to everything: active, suspended, confirmed, invited, rejected, archived etc... etc....etc ....  The **suspend** action has a well defined and unique use case and does not translate on acting on a generic user status, at least in our use case.

/users/1/actions/suspend
and 
/users/1/actions/enable

are really clear on what are going to do. 
I cannot find a way to generalize the enable/suspend concept into a resource that does not become too generic like **status**. While I see the pros of going restful on examples like:

DELETE /job_position_id/1/publication 

I do not find understandable an endpoint like:

DELETE /users/1/activation_status

I tend to think that when you cannot give a name to a thing sometimes it means that it does not exists. 
What could be stated as a limit between the 2 implementation? Could we state that when an action cannot be clearly identified into a resource (using common sense) is the case to prefer an action?

**Comment by openmosix** [comment]
As user that does not know *anything* about the API, what it does, etc. a method like

```
POST /users/1/actions/suspend
```

seems very clear in what it does. Without much furter context, I can guess from the verb and path what's its intention. I agree with @andreacfm that POST /users/1/status is not as explicit - his intentions are in the body of the request. As a user of the API, this means relying more on the API documentation to check what I can pass in the body to get the desired action.

**Comment by stefanoc** [comment]
@openmosix well, the same can be said of all endpoints that create/update resources, no? I _have_ to check the documentation to know what I can pass to ``PATCH /users/1`` when I want to update a user, after all.
Anyway, that was just an example to illustrate the point: you can (almost) always translate custom actions into standard CRUD actions on a resource. It just takes a bit of imagination :-)
But in case as simple as this I agree that it might not be worth the effort.

(And then a few months down the road you don't have a simple on/off status anymore, and you have to manage transitions, and you want to keep track of all changes, and you start thinking "_darn, I should have gone the RESTful way from the beginning!_")

:wink:

**Comment by andreacfm** [comment]
@stefanoc If you want to manage transitions you will probably do that with a **status** and at that point using **/users/1/status** makes a lot of sense. What is the resource? Status! Is very clear. No doubts.
But while managing transitions involves multiple statuses enable/suspend is an on/off switch that does not require any further specification. 
What if you use the **status** resource to implement the enable/suspend and after a few months you discover that you want to manage transitions that can accept dozens of values? The **status** resource will not be usable anymore because has been reserved to a case where it was not clear it would fit.
Btw I think that common sense always win in these situations so probably a generic statement that says we prefer restful representations with a fallback on actions (with actions namespace as a must) could fit.

**Comment by andreacfm** [comment]
I am still thinking about how we could write a sort of rule about this point.  Being only based on common sense and imagination is ok but does not guarantee a uniformity in the endpoint implementation through the all api.
Maybe writing down the pro and cons can help in adding some more context to the guideline about this aspect.

A couple of commonly used actions examples:

```ruby
POST /post/1/actions/publish
POST /users/1/actions/follow
```

Some positive aspects about this implementation:

* endpoints intentions are clear. The post will be published and the user will fe followed.
* without exposing and depending on any extra resource these are endpoints that looks solid and that will not probably require changes up to when the action is required. They will take care to perform the action no matter what are the consequences.

What are the practical and concrete aspects that could improve an api in converting these into a more restful implementation?

**Comment by openmosix** [comment]
@andreacfm what about a rule of thumb like:

* If you are adding an action that maps 1-1 with a CRUD, you add it as a resource + CRUD action
* If you can't find a 1-1 mapping with a resource for an action (without introducing resources that are a stretch or more boilerplate than the actual usage) you map it to an action endpoint

**Comment by taganaka** [comment]
Another rule of thumb is, generally speaking, to use `actions` instead of CRUD operations when a specific state depends on a specific value of an attribute of the target resource.

Using actions instead of changing the attribute value trough a PATCH operation will help also to write a more clean documentation.

Introducing more actions on the same resource will be about adding more endpoints each with it's own documentation rather than expanding the original endpoint documentation by listing new supported values

**Comment by liquid1982** [comment]
The reason I like

```
POST /article/:article_id/actions/publish
```

better than its REST compliant counterpart

```
POST /article/:article_id/article_publication
DELETE /article/:article_id/article_publication
```

is because doing things in "pure" REST style is a bit harder and could lead to inconsistencies due to poor abstractions / terms choices. This is where REST paradigm is usually difficult to apply...

I usually tend to prefer the REST way but I realize that the  `POST /article/:article_id/actions/publish` is much easier to read and understand.

Plus, we could think about exposing these actions with

```
GET /article/:article_id/actions
```

and make this endpoint behave like a resource with attributes mapped to actions that the API user could perform based on its access level and so on.

**Comment by andreacfm** [comment]
So we can probably state something like:

Prefer actions when the endpoint means to act on the resource atomically and does not requires further specifications/params. Actions MUST always be prefixed by the /actions namespace.
Example:

´´´ruby
POST /articles/1/actions/publish
´´´

Prefer a restful representation when the endpoint requires extra specifications and you can represent it as a CRUD action over a resource:
Example:

´´´ruby
POST /users/invitation
# requires params in the body
´´´

If this something we can agree. Feel free to express the concept in a better english.

**Comment by openmosix** [comment]
I'm ok with this. Moreover I feel CRUD actions should be pure CRUD - no side effects.
If you are creating a profile whose side effect is to create a JobApplication and various layers of business logic, I think that should be an action rather than a CREATE.
