### ISSUE TITLE
Feeling about UUIDs?

### ISSUE THREAD

**Issue by openmosix** [Gild/gild-api#8]
How do we feel about moving out of the current object IDs in favor of UUIDs?

https://github.com/Gild/gild-api#provide-resource-uuids

I'm a +1 on this but the impact is remarkable. We could probably easily address though with a concern.

cc: @taganaka @taganaka @tejo

**Comment by openmosix** [comment]
Note the spec requires the UUID to be unique across all resources

**Comment by andreacfm** [comment]
Generally I like this. The impact is huge but could be introduced slowly slowly moving things from v1 to v2.
A question. I am not an expert here but If I remember correctly a UUID is guaranteed to be unique up to when is generated on the same box. Is this correct?

**Comment by tejo** [comment]
I like uuids, I don't see any issues to start using them today with
something like this
https://github.com/Gild/tuna-api/commit/5e7829bbb199227d066b26d7877e9ee187afd44e
. Migrate the existing data to uuid it's a whole different story. It will
be nice if we can use them at DB level, but I don't know if mongo is
capable. @andreacfm I think you're right AFAIK.

**Comment by openmosix** [comment]
Ok, so I guess it's a yes :)

I'm a :+1: too on moving away from the current IDs to UUIDs. We need to probably use a different field, like 'uuid'. Agreed, we can move entity by entity when moving to v2.

**Comment by stefanoc** [comment]
@andreacfm I don't know about MongoDB, but a PostgreSQL UUID "is a 128-bit quantity that is generated by an algorithm chosen to make it very unlikely that the same identifier will be generated by anyone else in the __known universe__ using the same algorithm."

**Comment by openmosix** [comment]
So... there is a chance that in **another** universe the UUID will not be unique? In that case we might have inter-galatic API requests problems :trollface:

**Comment by openmosix** [comment]
@tejo the SecureRandom generates a random UUID. However we do not check for uniqueness among the data resources, but only on the single resource (from the code). While the collision chances are extremely low, it might happen - correct?

Also, I think we should investigate about overriding the Mongo _id - when I looked at that for Distill, I decided to use a different field (uuid) because it could create odd behaviors (the _id in Mongo is strongly opinionated - it has properties of time sequence, etc - while the uuid is randomic).

**Comment by stefanofontanelli** [comment]
For MongoDB I found this: http://3t.io/blog/best-practices-uuid-mongodb/

On Wed, Jun 24, 2015 at 11:24 AM, Luca Bonmassar <notifications@github.com>
wrote:

> So... there is a chance that in *another* universe the UUID will not be
> unique? In that case we might have inter-galatic API requests problems [image:
> :trollface:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gild/gild-api/issues/8#issuecomment-114971388>.
>



-- 
*Stefano Fontanelli*
Senior Engineer of Data & Infrastructure | Gild, Inc.
800-664-2366  | *cell *415-547-0722

465 California Street, Suite 1200
San Francisco, CA 94104
www.gild.com

**Comment by stefanofontanelli** [comment]
From: http://docs.mongodb.org/manual/faq/developers/


   -

   Use the _id field explicitly.

   MongoDB clients automatically add an _id field to each document and
   generate a unique 12-byteObjectId
   <http://docs.mongodb.org/manual/reference/glossary/#term-objectid> for
   the _id field. Furthermore, MongoDB always indexes the _id field. For
   smaller documents this may account for a significant amount of space.

   To optimize storage use, users can specify a value for the _id field
   explicitly when inserting documents into the collection. This strategy
   allows applications to store a value in the _id field that would have
   occupied space in another portion of the document.

   You can store any value in the _id field, but because this value serves
   as a primary key for documents in the collection, it must uniquely identify
   them. If the field’s value is not unique, then it cannot serve as a primary
   key as there would be collisions in the collection.


MongoDB doesn't do any assumption of the value inside _id, I think the
problem is who wrote the code (he/she assumed that _id is ordered by time
or is generated using time or whatever).
I know if you use a random hash instead of the default value for _id you
are going to lose the fact that you can sort by _id and get the data sorted
by time.


On Wed, Jun 24, 2015 at 11:27 AM, Luca Bonmassar <notifications@github.com>
wrote:

> @tejo <https://github.com/tejo> the SecureRandom generates a random UUID.
> However we do not check for uniqueness among the data resources, but only
> on the single resource (from the code). While the collision chances are
> extremely low, it might happen - correct?
>
> Also, I think we should investigate about overriding the Mongo _id - when
> I looked at that for Distill, I decided to use a different field (uuid)
> because it could create odd behaviors (the _id in Mongo is strongly
> opinionated - it has properties of time sequence, etc - while the uuid is
> randomic).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gild/gild-api/issues/8#issuecomment-114973069>.
>



-- 
*Stefano Fontanelli*
Senior Engineer of Data & Infrastructure | Gild, Inc.
800-664-2366  | *cell *415-547-0722

465 California Street, Suite 1200
San Francisco, CA 94104
www.gild.com

**Comment by andreacfm** [comment]
Pro of using a dedicated UUID field:

* we do not override the mongo _id exposing to unpredictable consequences now and in future mongo update
* we mange this keeping full control control on how, when and where to implement it. 
* we do not need to remap any Mongoid relation to use a different primary key. Even if we will expose the uuid in urls and we will require the uuid as identity in params we could leave Mongoid to manage the relations based on the default _id implementation (make sense?).  

Cons:

* since the _id is indexed by default using the uuid field as "defined" primary key will force to add an extra index.

**Comment by openmosix** [comment]
@stefanofontanelli 

The problem is (below) several drivers expect the _id in a specific format (for example to extract created_at). Given we use multiple drivers (python, ruby) I'd be afraid of that.



Yes, there is a catch

You might run into problems when working with UUIDs in multi-platform/multi-language environments because accessing your database from different programming languages using different MongoDB drivers might not always be safe, as we will demonstrate below. Furthermore, you should be careful when working with UUID data types in third-party MongoDB management software because only a few MongoDB tools take due care in handling UUID data types.

MongoDB drivers usually convert UUIDs between their Binary database representation and the language specific UUID data type. Initially the encoding method was platform specific and wasn’t consistently implemented across different MongoDB drivers.

Example:

An example UUID created and displayed in a Java application would be shown as follows:

00010203-0405-4007-8009-0A0B0C0D0E0F

The MongoDB Java driver (version 2.9.1 in this example) will convert it to a Binary database representation and store it with the following byte order:

07 40 05 04 03 02 01 00 0F 0E 0D 0C 0B 0A 09 80

However, the C# driver used to access the same field will return and display the following:

04054007-0203-0001-0F0E-0D0C0B0A0980

You’ll notice the representation of the same UUID differs depending on the platform used to access it.

As long as you’re not editing those UUIDs on both ends, you shouldn’t experience any serious problems (besides confusion when analysing your data). However, if one day you do edit a UUID, you’ll very likely run into issues that can be very difficult to locate and debug because you’ll essentially be dealing with scrambled data.

**Comment by openmosix** [comment]
@andreacfm @taganaka I made a first implementation of the UUID here:

https://github.com/Gild/tuna-api/pull/1079/files#diff-dafbd91a4ac0f01d84efb64fe9bb438cR2

What do you think? Good enough?

**Comment by andreacfm** [comment]
@openmosix Overall looks good to me. I just added a question on the commit.
